spring.application.name=foosball

# Challonge Basic Auth credentials
challonge.username=${CHALLONGE_USERNAME}
challonge.api-key=${CHALLONGE_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AWS
aws.region=${AWS_REGION}
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

aws.s3.buckets.tournaments=${AWS_S3_BUCKET_TOURNAMENTS}
aws.s3.buckets.players=${AWS_S3_BUCKET_PLAYERS}
aws.s3.buckets.documents=${AWS_S3_BUCKET_DOCUMENTS}

# Load local overrides if application-local.properties exists (gitignored)
spring.config.import=optional:file:./application-local.properties
