spring.application.name=foosball

spring.datasource.url=jdbc:postgresql://localhost:5432/ktsa_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG

jwt.secret=ktsasupersecretjwtkeysupersecretjwtkey123

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anjali206542@gmail.com
spring.mail.password=yctlzrfuweqewuru
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true









#AWS
#aws.s3.bucket-name=dev-ktsa-public-assets
aws.region=ap-south-1
aws.access-key-id=${AWS_ACCESS_KEY}
aws.secret-access-key=${AWS_SECRET_KEY}

aws.s3.buckets.tournaments=ktsa-tournaments-bucket
aws.s3.buckets.players=ktsa-players-bucket
aws.s3.buckets.documents=ktsa-documents-bucket